activity: 
  name: '/help'
  type: 'Playing'
  url: 'https://www.twitch.tv/your_channel' # if streaming or watching
owners:
  - "311929179186790400"
  - "1174678858444836907"
  - "422418878459674624"
systemServer:
  - "1313550337474429001"
intents:
  - Guilds
  - GuildMembers
  - GuildModeration
  - GuildBans
  - GuildExpressions
  - GuildEmojisAndStickers
  - GuildIntegrations
  - GuildWebhooks
  - GuildInvites
  - GuildVoiceStates
  - GuildPresences
  - GuildMessages
  - GuildMessageReactions
  - GuildMessageTyping
  - DirectMessages
  - DirectMessageReactions
  - DirectMessageTyping
  - MessageContent
  - GuildScheduledEvents
  - AutoModerationConfiguration
  - AutoModerationExecution
  - GuildMessagePolls
  - DirectMessagePolls
partials:
  - Reaction
  - Message
baseCommandsPrefix: "?"
